repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0 # TODO: change to v4.4.0?
    hooks:
    -   id: trailing-whitespace
    -   id: check-merge-conflict
-   repo: https://github.com/PyCQA/flake8
    rev: 3.8.4 # TODO: change to 6.0.0?
    hooks:
    -   id: flake8
        name: Check project styling
        args:
        - --max-line-length=160
-   repo: https://github.com/PyCQA/isort
    rev: 5.11.5 # TODO: Change to 5.12.0?
    hooks:
    -   id: isort
        name: Sort python imports (shows diff)
        args: ["-c", "--diff"]
    -   id: isort
        name: Sort python imports (fixes files)
