[tox]
envlist = py38,py39,py313,packaging,pre-commit-check

passenv = GITHUB_*

[testenv:packaging]
deps =
  twine
commands =
  python setup.py sdist bdist_wheel --universal
  twine check dist/*

[testenv:pre-commit-check]
deps =
  pre-commit
commands =
  pre-commit run --all-files

[gh-actions]
python =
  3.13: py313, packaging, pre-commit-check
